### ISSUE TITLE
Coreferential chains should have the same wiki anchor

### ISSUE THREAD

**Issue by Marketa-Lopatkova** [ufal/UMR#10]
Coreferential chains should have the same wiki anchor - is it possible to implement this check in the validator?

**Comment by dan-zeman** [comment]
The validator can now (ccec09467364d73cd058e227992932b9033d3b8b) optionally print the information about coreference clusters (i.e., sets of concept nodes that are said to refer to the same entity). This is not an error report (if required, it is shown regardless whether the coreference annotation is correct or not) and it is printed to STDOUT.

For example:

``` bash
python tools\validate.py --print-clusters data\czech\mf920922-133_estonsko-ML.txt > clusters.txt
```

prints errors to STDERR as usual but it also prints the coreference info (even if it is correct) to STDOUT, which is redirected to the file clusters.txt. At present, the contents of the file is as follows:

```
Coreference cluster 's1p': 
  s1p ( / publication-91) wiki '' line 7
  s2p ( / publication-91) wiki '' line 44
  s3p ( / publication-91) wiki '' line 74
Coreference cluster 's1c': 
  s1c ( / country) wiki 'Q191' line 11
  s2c (ESTONSKO / country) wiki 'Q191' line 46
  s3c ( / country) wiki 'Q191' line 78
  s5c (v Estonsku / country) wiki 'Q191' line 172
  s7r (republiky / republika) wiki 'Q191' line 312
Coreference cluster 's1v': 
  s1v (volili / volit-001) wiki 'Q372557' line 8
  s3v (volili / volit-001) wiki 'Q372557' line 75
  s5v (V volbách / volit-001) wiki 'Q372557' line 164
Coreference cluster 's1p2': 
  s1p2 (Estonci / person) wiki '' line 10
  s3p2 (Estonci / person) wiki '' line 77
Coreference cluster 's1p3': 
  s1p3 (parlament / parlament) wiki 'Q217799' line 15
  s3p3 (parlament / parlament) wiki 'Q217799' line 82
  s5p (parlamentních / parlament) wiki 'Q217799' line 166
Coreference cluster 's5b': 
  s5b (blok Vlast jehož / blok) wiki 'Q163347' line 146
  s6b (pro blok Vlast / blok) wiki 'Q163347' line 258
Coreference cluster 's6p6': 
  s3g ( / UNKNOWN) wiki '' line 294
  s6p6 (v parlamentu / parlament) wiki 'Q217799' line 252
```

**Comment by dan-zeman** [comment]
Done. Now it prints errors like this (note that the Wikidata Q-codes are resolved to entity names only if the Python requests library is installed; try `pip install requests`):

[Line 82]: [L3 Document coref-wiki-mismatch] The node 's3p3' has wikidata link Q217799 (Riigikogu) but it is coreferential with node 's1p3' whose wikidata is Q191 (Estonia).
