### ISSUE TITLE
Person nodes in modal annotation

### ISSUE THREAD

**Issue by fjambe** [ufal/UMR#12]
The validator returns the following errors when it finds a `person` node in doc-level modal annotation, because it considers it to be an event with missing attributes:

`[L3 Sentence missing-attribute] Missing attribute :aspect. Node s7p is an event because it participates in :modal relation :neutral-affirmative.`
`[L3 Sentence missing-attribute] Missing attribute :modal-strength. Node s7p is an event because it participates in :modal relation :neutral-affirmative.`

The error above comes from Latin data. However, the same annotation is found in the guidelines, e.g.

```
Rob thinks the dog escaped through the fence.
(t/ think-01
	:ARG0 (p/ person
		:name (n/ name :op1 "Rob"))
	:ARG1 (e/ escape-01
		:ARG0 (d/ dog
			:ref-number Singular)
		:path (f/ fence)
		:aspect Performance
		:modpred t)
	:aspect State
	:modstr FullAff)
(s/ sentence
	:temporal ((DCT :overlap s1t)
		   (s1t :before s1e))
	:modal ((AUTH :FullAff s1p)
		**(s1p :FullAff s1t)**
		(s1t :Unsp s1e)))
```

So `person` nodes (or in general non-events?) should probably be allowed in modal annotation without the validator raising an error.

**Comment by dan-zeman** [comment]
Hmm, [that makes sense](https://github.com/ufal/umr-guidelines/blob/master/guidelines.md#part-4-3-modal-dependency). I will remove the test.
