### ISSUE TITLE
Events vs. non-events

### ISSUE THREAD

**Issue by dan-zeman** [ufal/UMR#4]
We spend a lot of energy on [figuring out, what is or is not an event in UMR](https://github.com/ufal/UMR/blob/main/doc/eventive-concepts.md).

I'm starting to wonder what are the practical consequences of this distinction? We probably should anchor all processes and states in a valency lexicon such as [SynSemClass](https://lindat.mff.cuni.cz/services/SynSemClass40/SynSemClass40.html), regardless their information packaging. If the sentence mentions their arguments, they will get the corresponding `:ARGX` relations, be they events or not. So the concept node will probably look the same whether we say it is an "eventive concept" or not.

One side question is whether we should create an event node when we see a noun derived from a verb and denoting a participant in a process (such as _teacher_ – see https://github.com/umr4nlp/umr-guidelines/issues/16).

Any other consequences?

**Comment by Marketa-Lopatkova** [comment]
Definitely, all **processes** should be anchored in a valency lexicon (regardless their information packaging).

As for **states** - according to the [guidelines, sect 3-1-1](https://github.com/umr4nlp/umr-guidelines/blob/master/guidelines.md#part-3-1-1-eventive-concepts), only those packaged as predication should be considered as events.
Which is a problem as it is not clear 
- how broad the definition of predication is and 
-  and where is a boundary between predication and modification (_the tall man_ vs. _the man who is tall_).

Treating all states as events would thus violate the guidelines - are we allowed to do this?  

Or do we want move the line and apply a bit clearer criterion (at least from our point of view):
- to  consider all states in an attribute position (_the tall man_)  as non-events
- states in verbonominal constructions (_Those thorns are sharp._) as events, regardless their syntactic status main clause/relative clause ( _the man is tall_, _the man who is tall_).

However, this would violate the [guidelines, sect 3-1-1](https://github.com/umr4nlp/umr-guidelines/blob/master/guidelines.md#part-3-1-1-eventive-concepts) as well.

As for **entities** - the answer we got so far is based in morphology (a noun derived from a verb), which is probably not what should be considered as the main criterion in UMR??

**Comment by dan-zeman** [comment]
> As for **states** - according to the [guidelines, sect 3-1-1](https://github.com/umr4nlp/umr-guidelines/blob/master/guidelines.md#part-3-1-1-eventive-concepts), only those packaged as predication should be considered as events. Which is a problem as it is not clear
> 
> * how broad the definition of predication is and
> * and where is a boundary between predication and modification (_the tall man_ vs. _the man who is tall_).
> 
> Treating all states as events would thus violate the guidelines - are we allowed to do this?

My question was different: what does it mean to treat a state as event? Surely it is not the presence of the state in a particular lexicon (SynSemClass). The lexicon will say that `chytrý-01` (_chytrý_ "clever") is a state. It does not say that it is an event (it cannot, because being an event depends on context.) We will refer to that lexicon entry from eventive mentions of the state (predication) as well as from the non-eventive ones. So what exactly would we be violating?

**Comment by dan-zeman** [comment]
> As for **entities** - the answer we got so far is based in morphology (a noun derived from a verb), which is probably not what should be considered as the main criterion in UMR??

That was my first reaction, too.

But then I thought, hey, this is not just about morphology, this is about explaining semantics of morphology. And semantics does belong to UMR. Similarly, relative clauses _(the man who teaches)_ are syntactic rather than semantic construct, but we try to explain their semantics in UMR.

**Comment by dan-zeman** [comment]
Based on the examples in the UMR guidelines, processes expressed as finite verbs can also occur without their arguments if the arguments are not known. Unlike in the Prague tectogrammatical layer, you do not generate a node for every argument that is specified in the valency lexicon.

**Comment by Marketa-Lopatkova** [comment]
> Zdenka: Well, not sure about it;  as far as I know, UMR DOES work with some morfological categories, see ex. 3-2-1-1 (4b) in https://github.com/umr4nlp/umr-guidelines/blob/master/guidelines.md#part-3-2-1-1-stage-0

As far as I understand it,
UMR should definitely work with those morphological categories that has clear semantic meaning (as , e.g., grammatemes in PDT, also called "pojmenovávací" ) ...like the person (to distinguish different personal pronouns), number (sg, pl), etc.

But it should not considered those morphological categories that serve just as a syntactic glue ("usouvztažňující" in Czech terminology) - like case with nouns, gender, number and case with adjectives.
http://pfyziolmysl.upol.cz/?p=4607

Thus, according to me, it should not consider part of speech categories as they depend on a position in a sentence ( for example, a verb and its nominalization should be annotated in the same styl as a semantic verb).

**Comment by Marketa-Lopatkova** [comment]
Based on Julia's email (Dec 6, 2023),  the consequences of being designated an 'event' in UMR are:

-    roleset use: if rolesets are being used, qualifying as an 'event' means that it is reasonable to represent the expression in question using a roleset. (But note that it is also possible to use rolesets for expressions that do not qualify as 'events'. For example, in English, the roleset 'hunger-01' has been used to cover expressions 'hunger-verb', 'hunger-noun', and 'hungry-adjective'. According to the guidelines, 'hungry' in the sentence 'the hungry man' is a state in modification, and therefore doesn't count as an 'event'. But the roleset for 'hunger' is still semantically relevant-- both in terms of sense disambiguation and in terms of the allowed argument structure. What I've been proposing (and which seems to be agreed to by everyone now) is that we should be allowed to use the 'hunger-01' roleset here. 
-    :aspect annotation: 'events' receive aspect annotation. 
-    :modal-strength annotation: 'events' receive modal annotation in the sentence and document graphs
-    :temporal dependency annotation: 'events' qualify for placement in the document-level temporal dependency.  

We have arrived to preliminary conclusions as sketched in Issue [#8](issues/8)
